name: Deploy Vue to GitHub Pages

on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 👈 这里改成了 22，满足 Vite 的要求

      - name: Install and Build 🔧
        run: |
          cd my-blog
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: my-blog/dist # 👈 确保这里的路径是对的
          branch: gh-pages